export const NO_MAGIC_INSTANCE = 1000
export const NO_MAGIC_TOKEN = 1001
export const NO_MAGIC_USER = 1002

export const NOT_ISOMORPHIC = 2000

export const UNABLE_TO_LOGIN = 3000

export const ENDPOINT_UNAVAILABLE = 4000

export const ERRORS = {
  NO_MAGIC_INSTANCE,
  NO_MAGIC_TOKEN,
  NO_MAGIC_USER,
  NOT_ISOMORPHIC,
  UNABLE_TO_LOGIN,
  ENDPOINT_UNAVAILABLE,
}
