import Head from 'next/head'
import Footer from 'components/Footer'
import Navbar from 'components/Navbar'
import useLogin from 'hooks/useLogin'
import useNav from 'hooks/useNav'

export default function Home() {
  const $metadata = useLogin()
  const { hideNav } = useNav()
  return (
    <div className="min-h-screen flex flex-col">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar fill="black" className="bg-iforange text-black" />

      <main className="bg-iforange flex-1">
        <h1 className="text-2xl">
          {$metadata && $metadata.email
            ? `Welcome to Testnet, ${$metadata.email}!`
            : `Welcome to Testnet.`}
        </h1>
      </main>

      <Footer />
    </div>
  )
}
