name: Integration Tests ⚡️

on: [pull_request]

jobs:
  test_setup:
    name: Test setup
    runs-on: ubuntu-latest
    outputs:
      preview_url: ${{ steps.waitForVercelPreviewDeployment.outputs.url }}
    steps:
      - name: Wait for Vercel preview deployment to be ready
        uses: patrickedqvist/wait-for-vercel-preview@master
        id: waitForVercelPreviewDeployment
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 60
  test_e2e:
    name: Test end-to-end
    needs: test_setup
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Cache Cypress 
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/Cypress
          key: cache-${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: Install Node.js dependencies
        run: yarn
      - name: Run Cypress
        uses: cypress-io/github-action@v2
        with:
          config: baseUrl=${{ needs.test_setup.outputs.preview_url }}
          install: false # We test a live preview URL, no need to install packages
