name: Validate

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-checks:
    name: Run programmatic checks
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install Node.js dependencies
        run: yarn

      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          eslint: true

      - name: Run E2E Tests with Cypress
        uses: cypress-io/github-action@v2
